# Generated by Django 3.1.7 on 2021-04-05 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('user_type', models.IntegerField(default=1)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
