# Generated by Django 3.1.7 on 2021-06-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_loginuser_sig'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginuser',
            name='email',
            field=models.EmailField(default='testemail@email.com', max_length=254),
        ),
    ]
