# Generated by Django 3.1.7 on 2021-05-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('productName', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('merchantName', models.CharField(max_length=32)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled')], max_length=30)),
                ('inventory', models.IntegerField(default=999)),
                ('address', models.TextField(blank=True, null=True)),
                ('totalprice', models.FloatField()),
            ],
        ),
    ]
