# Generated by Django 3.1.7 on 2021-05-30 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_productid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fromAddress',
            field=models.TextField(default='test from address'),
        ),
        migrations.AddField(
            model_name='order',
            name='fromPhoneNumber',
            field=models.CharField(default=12233345556, max_length=11),
        ),
        migrations.AddField(
            model_name='order',
            name='profit',
            field=models.FloatField(default=500),
        ),
        migrations.AddField(
            model_name='order',
            name='toPhoneNumber',
            field=models.CharField(default=12233345556, max_length=11),
        ),
    ]
