# Generated by Django 3.1.7 on 2021-06-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20210530_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ooid',
            field=models.CharField(default='no ooid', max_length=600),
        ),
    ]
