# Generated by Django 3.1.7 on 2021-06-07 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_ooid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Payed', 'Payed'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered'), ('Canceling', 'Canceling'), ('Canceled', 'Canceled')], max_length=30),
        ),
    ]
