# Generated by Django 3.1.7 on 2021-04-08 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('status', models.IntegerField(default=1)),
                ('merchantName', models.CharField(max_length=32)),
                ('price', models.FloatField()),
                ('dateInProduction', models.DateField()),
            ],
        ),
    ]
