# Generated by Django 3.1.7 on 2021-05-31 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.IntegerField(db_index=True)),
                ('customerId', models.IntegerField()),
                ('neirong', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('status', models.IntegerField(default=1)),
                ('merchantName', models.CharField(max_length=32)),
                ('price', models.FloatField()),
                ('dateInProduction', models.DateField()),
                ('briefDescription', models.CharField(default='', max_length=255)),
                ('imageUrl', models.CharField(default='', max_length=500)),
                ('inventory', models.IntegerField(default=999)),
                ('stars', models.FloatField(default=0)),
                ('starsNumber', models.IntegerField(default=0)),
                ('basePrice', models.FloatField(default=575)),
            ],
        ),
    ]
