# Generated by Django 3.1.7 on 2021-04-08 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='briefDescription',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='imageUrl',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='inventory',
            field=models.IntegerField(default=999),
        ),
        migrations.AddField(
            model_name='product',
            name='stars',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='starsNumber',
            field=models.IntegerField(default=0),
        ),
    ]
