# Generated by Django 3.1.7 on 2021-05-31 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='orderId',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='stars',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
