# Generated by Django 3.2 on 2021-06-08 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210531_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='classword',
            field=models.CharField(default='all;', max_length=100),
        ),
    ]
