# Generated by Django 3.1.7 on 2021-05-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.IntegerField(db_index=True)),
                ('path', models.CharField(max_length=512)),
            ],
        ),
    ]
