# Generated by Django 3.1.7 on 2021-05-30 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pic',
            name='productId',
            field=models.IntegerField(),
        ),
    ]
