# Generated by Django 3.1.7 on 2021-05-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingCart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcartp',
            name='productName',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='shoppingcartp',
            name='username',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
